import Footer from '@/components/Footer';
import Header from '@/components/Header';
import { ChakraProvider } from '@chakra-ui/react';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head />
      <body>
        <ChakraProvider>
          <Header />
          {/* Define the overall layout of the application */}
          <div className="flex min-h-screen flex-col bg-[#000000] text-[#f7fafcd0]">
            <main>{children}</main>
          </div>
          <Footer />
        </ChakraProvider>
      </body>
    </html>
  );
}
